### ISSUE TITLE
catching classes that do not inherit from BaseException is not allowed

### ISSUE THREAD

**Issue by zarlicho** [Logitech/logiPy#10]
i get an error like this:

Traceback (most recent call last):
  File "C:\Users\Diva Creative\.conda\envs\tensorenviron\lib\site-packages\logipy\logi_led.py", line 237, in <module>
    led_dll = load_dll()
  File "C:\Users\Diva Creative\.conda\envs\tensorenviron\lib\site-packages\logipy\logi_led.py", line 234, in load_dll
    raise SDKNotFoundException('The SDK DLL was not found.')
TypeError: SDKNotFoundException() takes no arguments

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bgled.py", line 1, in <module>
    from logipy import logi_led
  File "C:\Users\Diva Creative\.conda\envs\tensorenviron\lib\site-packages\logipy\logi_led.py", line 238, in <module>
    except SDKNotFoundException as exception_sdk:
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by MarkoP-engineering** [comment]
Exactly the same issue!
