### ISSUE TITLE
Missing environment variable error in x86

### ISSUE THREAD

**Issue by ogay** [Logitech/logiPy#3]
On Windows 7 32-bit logi_led.py fails because of missing ProgramW6432 environment variable.

See log below:

c:\Users\ogay\Desktop\logiPy>c:\Python27\python.exe bla.py
Traceback (most recent call last):
  File "bla.py", line 4, in <module>
    from logipy import logi_led
  File "c:\Users\ogay\Desktop\logiPy\logipy\logi_led.py", line 234, in <module>
    led_dll = load_dll()
  File "c:\Users\ogay\Desktop\logiPy\logipy\logi_led.py", line 226, in load_dll
    subpath_lgs = os.environ['ProgramW6432'] if os.environ['ProgramW6432'] else os.environ['ProgramFiles']
  File "c:\Python27\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'PROGRAMW6432'

c:\Users\ogay\Desktop\logiPy>

**Comment by ogay** [comment]
Fix submitted in this [pull request](https://github.com/Logitech/logiPy/pull/4).
